version: "2"
services:
    elastic:
        build: .docker/elasticsearch
        container_name: bot-track-elastic
        environment:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - bootstrap.memory_lock=true
          - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
            mem_limit: 1g

    webserver:
        image: nginx
        container_name: bot-track-webserver
        working_dir: /application
        volumes:
          - .:/application
          - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "80:80"
        command: /bin/bash -c "nginx -g 'daemon off;'"

    php-fpm:
        build: .docker/php/fpm
        container_name: bot-track-php
        working_dir: /application
        volumes:
          - .:/application
          - ./.docker/php/fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini

    parser1:
        build: .docker/php/cli
        container_name: bot-track-parser-1
        working_dir: /application
        volumes:
          - .:/application
        command: /bin/bash -c 'php /application/src/cli/parser.php'

    parser2:
        build: .docker/php/cli
        container_name: bot-track-parser-2
        working_dir: /application
        volumes:
          - .:/application
        command: /bin/bash -c 'php /application/src/cli/parser.php'

    rabbit:
        image: rabbitmq
        container_name: bot-track-rabbit
        environment:
          - RABBITMQ_ERLANG_COOKIE='secret_cookie'
          #- RABBITMQ_DEFAULT_USER='rabbit'
          #- RABBITMQ_DEFAULT_PASS='rabbit'